# develop에서 main으로 pr머지했을 때
# lint 검사
# lint 통과 시, 빌드
# 빌드 완료 시, aws에 배포

name: my workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # Node 16.x를 사용합니다.
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      # 모듈을 설치합니다.
      - name: Install packages
        run: rm -rf node_modules && yarn install --frozen-lockfile

      # 린트 체크
      - name: Lint
        run: yarn lint

      - name: Build # React Build
        run: yarn build

      - name: Deploy # S3에 배포하기
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://top17-test # 자신의 레포지토리로 변경해주세요.
